### PR TITLE
added flat and booking models

### PR DESCRIPTION
**Pull request by tomag1985**
@Joacocasanova @ropicaza hechos los modelos de flat y booking con sus validaciones!

### CODE REVIEW

**Comment by Joacocasanova** [comment]
@tomag1985 Please review conflicts before making a pull request

**Comment by tomag1985** [comment]
@Joacocasanova please review the new code

**Review by Joacocasanova — DISMISSED** [review]

**Review by Joacocasanova — CHANGES_REQUESTED** [review]
@tomag1985  we have to add associations, and please fix typo on "presence :true" , it should  be `presence: true`

**Comment by tomag1985** [comment]
user and flats seed added.. models association and validations solved!

**Review by Joacocasanova — APPROVED** [review]

**Pull request merged**
